### ISSUE TITLE
Move types from DefinitivelyTyped to here 🙇🏽‍♂️

### ISSUE THREAD

**Issue by lluia** [nextauthjs/next-auth#1649]
## Summary 💭

We've been maintaining the types for this library on [DefinitivelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/af3a9697e41e3594f012525909beef1812588389/types/next-auth). It's been working ok so far as there was no interest in moving the source code to TS to get the types automatically generated. 

However, it's challenging 🧯 to keep the types up to date, given they live in a separate repository and rely on updates from contributors. After speaking with @balazsorban44, we think we can spike to move the types to a folder here (`types/`), get them linted through [`dtslint`](https://github.com/Microsoft/dtslint) and integrated with the build pipeline 🎊

## Tasks ✅

- [x] Move types to this repo, to a folder called `types` in the root _(suggestions welcome)_
- [x] Add `dtslint` and add a command to lint the types
  - [x] add it to the CI
- [x] Modify `package.json` to declare types for the package
- [x] Modify build script to get types into `/dist` _(suggestions welcome)_
- [x] Make a **beta release** and verify everything works correctly
- [x] Update the `README` and website to explain types are now part of the `next-auth` package
- [x] Test whether the new types take precedence over `@types/next-auth`
- [x] fix typos
- [x] Sort-out module augmentation issues
- [ ] Deprecate `@types/next-auth`
- [ ] Release new types on `next-auth`

## Additional context 📓

@JuanM04 @euxn23, you've been actively maintaining the types in **DefitnivelyTyped**. Would you be interested in joining/supporting this effort? (any other contributors welcome 💚)

( cc. @iaincollins )

- Current type definitions on [DefinitivelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/af3a9697e41e3594f012525909beef1812588389/types/next-auth) _(what you get when installing `@types/next-auth`)_
- [`dtslint`](https://github.com/Microsoft/dtslint)

**Comment by lluia** [comment]
Relates to #1650

**Comment by JuanM04** [comment]
I'll be glad to help. Should we make PRs to `main` or to another branch?

**Comment by balazsorban44** [comment]
@JuanM04, awesome! I think we should create a `beta` branch.

**Comment by JuanM04** [comment]
I was looking at the repo and there are lots of `.d.ts` files around. I was wondering, migrating all the repo to TypeScript isn't an option, right?

**Comment by balazsorban44** [comment]
not at the moment, no. we would like to keep the source code and types decoupled for now. 😊 we will see how that goes.

**Comment by lluia** [comment]
@JuanM04 super 💯 , if you make PR and merge on `beta`, can you then update the ✅  on this issue accordingly? In this way we can keep track on where we're at in the migration 🙇🏽‍♂️

**Comment by balazsorban44** [comment]
Added the `beta` branch https://github.com/nextauthjs/next-auth/tree/beta, it can now be targeted in PRs.

**Comment by JuanM04** [comment]
@balazsorban44 amazing! My client gave me some work to do, but I'll try to help you as much as I can

**Comment by balazsorban44** [comment]
I think the next step after this should be to update the documentation to reflect the types 1 to 1. The most optimal solution would be if we could somehow extract the type of information, and inject it right into the docs.

For instance look at the Instagram provider I tweaked with JSDoc:

https://github.com/nextauthjs/next-auth/blob/main/src/providers/instagram.js

It basically contains all the info that is in https://github.com/nextauthjs/next-auth/blob/main/www/docs/providers/instagram.md

And so https://github.com/nextauthjs/next-auth/blob/main/www/docs/providers/instagram.md could be derived from the source code, keeping it always up-to-date.

**Comment by balazsorban44** [comment]
Fixed most of the typos, added even more links to documentation.

Also checked, when `@types/next-auth` is installed, built-in types *WILL* take precedence
