### ISSUE TITLE
Update TS example repo and maintain it

### ISSUE THREAD

**Issue by lluia** [nextauthjs/next-auth#1650]
## Summary 💭

We have an empty repo on the org [`next-auth-typescript-example`](https://github.com/nextauthjs/next-auth-typescript-example), the purpose of it was to mirror [`next-auth-example`](https://github.com/nextauthjs/next-auth-example) and serve as a quickstart for projects using `next-auth` on a Typescript environment.

Unfortunately, the PRs on it never got reviewed. Right now, our idea is to get it up and to run and use it as well as a playground to test the types manually. 

cc. @iaincollins @balazsorban44 

## Tasks ✅

- [ ] ~Review [open PRs](https://github.com/nextauthjs/next-auth-typescript-example/pulls) and try to get them merged~
  - [ ] ~cc. @JuanM04 @xiaooye~ 
- [x] Update the example to mirror  `next-auth-example`
- [x] Brainstorm how to better keep both in sync

**Comment by lluia** [comment]
Relates to #1649

**Comment by balazsorban44** [comment]
One idea, what if we have one repo for both examples? a javascript and a typescript folder in the root?

**Comment by lluia** [comment]
@balazsorban44 maybe 🤔 ; I think the main goal though of the example repo is to clone it and play with the library straight away? ( _hence having two apps on the repo would defeat a bit the purpose of it?_ )

**Comment by balazsorban44** [comment]
hmm, might be true. Another other idea, add a PR template to each repos and remind the PR creator to mirror their work to the other repo if it's relevant.

**Comment by lluia** [comment]
We created an example repo for **Typescript** users, check it out 💚

https://github.com/nextauthjs/next-auth-typescript-example
