### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#1792]
## Issues :ticket: :
  - [x] Add TypeScript issue template
  - [x] Reword current templates
  - [x] Require bug reports to have a reproduction
  - [ ] Check out Beta issue templates
## Automation :robot: :
  - [x] introduce [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners), add @lluia and @balazsorban44 for TypeScript
  - [x] Add Node 16 to workflows (#1790)
  - [x] Remove Node 10 from workflows (#1790)
  - [x] auto label TypeScript PRs with labeler
## Bundle :package: 
  - [ ] check out how to build different bundles (
![image](https://user-images.githubusercontent.com/18369201/115469852-aa5b2b00-a235-11eb-890e-3a4b2f9ada4a.png)
, https://docs.skypack.dev/package-authors/package-checks#esm)
## Docs :books:
  - [x] improve mobile view (
![image](https://user-images.githubusercontent.com/18369201/115469980-e098aa80-a235-11eb-8a77-8f92f9331660.png)
)
 - [x] upgrade Docosaurus to latest (#1826)
 - [ ] Discuss possible restructurings
 - [ ] improve branding (@lluia? )

## Other repos
  - [x] improve/fix/automate https://github.com/nextauthjs/adapters releases
  - [x] gitignore package-lock.json in https://github.com/nextauthjs/next-auth-example
