### ISSUE TITLE
Umbrella issue for adapter/provider guides/concepts

### ISSUE THREAD

**Issue by balazsorban44** [nextauthjs/next-auth#6876]
### What is the improvement or update you wish to see?

- [ ] Fetch-based Adapter guide (https://github.com/nextauthjs/next-auth/issues/6521#issuecomment-1413073645)
- [ ] Federated logout guide under `/guides/providers/federated-logout` (https://github.com/nextauthjs/next-auth/discussions/3938)
- [ ] Federated logout concept under `/concepts/oauth#federated-logout` (https://github.com/nextauthjs/next-auth/discussions/3938)
- [ ] Token rotation concept under `/concepts/oauth#token-rotation` (https://authjs.dev/guides/basics/refresh-token-rotation)

### Is there any context that might help us understand?

#6612
